name: mkgu
channels:
- defaults
dependencies:
- xarray
- numpy
- pandas
- six
- requests
- boto3
- netcdf4
- scipy
- scikit-learn
- networkx
- pytest
- jupyter
- pip:
  - pathos
  - git+https://github.com/mschrimpf/caching
